[tool.poetry]
name = "axis"
version = "0.1.0"
description = ""
authors = ["jdluque <jdluque@leitat.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
# protobase = { path = "../protobase", develop = true }
antlr4-tools = "^0.2.1"
antlr4-python3-runtime = "^4.13.2"
interegular = "^0.3.3"

#egglog = "^7.1.0"
pyyaml = "^6.0.2"
semver = "^3.0.4"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.28.0"
rich = {extras = ["jupyter"], version = "^13.9.4"}
watchdog = "^3.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
