[tool.poetry]
name = "axis"
version = "0.1.0"
description = ""
authors = ["jdluque <jdluque@leitat.org>"]
readme = "README.md"

[[tool.poetry.packages]]
include = "axis"
from = "src"

[tool.poetry.dependencies]
python = "^3.13"
protobase = { path = "packages/protobase", develop = true }
antlr4-tools = "^0.2.1"
antlr4-python3-runtime = "^4.13.2"
interegular = "^0.3.3"

#egglog = "^7.1.0"
pyyaml = "^6.0.2"
semver = "^3.0.4"
ipython = "^9.10.0"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.28.0"
rich = {extras = ["jupyter"], version = "^13.9.4"}
watchdog = "^6.0.0"
pyright = "^1.1.408"
textual = "^0.83.0"

[tool.pyright]
exclude = ["src/axis/syn/grammar/*.py"]

[tool.poetry-monoranger-plugin]
enabled = true
monorepo-root = "."
version-pinning-rule = "=="

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
