%import common.CNAME -> ID
%import common.NUMBER -> NAT
%import common.WS
%ignore WS

?expr: opchain{composition{ \
    prefix{suffix{atom}}, \
    prefix{suffix{atom}} \
}}


?opchain{x}: addition{prduct{x}}

?addition{next}: next
    | next (/[+-]/ next)+ -> addition

?product{next}: next
    | next (/[*\/%]/ next)+ -> product

?prefix{next}: next
    | /-+$#~!/+ next -> prefix

?composition{l, r}: r
    | l composition{l,r} -> composition

?suffix{next}: next 
    | suffix{next} "." ID -> member
    | suffix{next} "[" next "]" -> index
    | suffix{next} "(" tuple_entry ("," tuple_entry)* ","? ")" -> call

?atom{next}: ID -> id
    | NAT -> nat


?term{next}: ID -> id
    | NAT -> nat



suff: "." ID -> property
    | "::" ID -> attribute
    | "[" expr "]" -> index
    | tuple -> call
    | suite -> 



suite: "{" expr "}"

tuple: "(" tuple_entry ("," tuple_entry)* ","? ")" -> tuple
?tuple_entry: [ID ":"] expr -> tuple_entry
    | "{" expr "}" ":" expr -> tuple_entry_dynkey

 
//
// a.b { x,y,z -> x+y+z }
//
//
//
// 

//sin[T] { x: ,y -> }