%import common.WS
%import common.CNAME -> ID
%import common.NUMBER -> NUM
%ignore WS

//?expr: complex_expr
//?simple_expr: construct{composition{operators{simple_suffix{atom}}}}
//?complex_expr: construct{composition{operators{complex_suffix{atom}}}}

//?expr: composition{ operators{ suffix{atom}} }
?expr: composition{  suffix{atom} }


//?expr: bw_composition{ operators{ fw_composition{atom}} }

?atom: "_" -> wild
    | ID -> id
    | NUM -> num
    | tuple 
    | shape
    | suite
    | if | for
    

?suffix{x}: x
    //| tuple | shape | suite
    | suffix{x} "?" -> check
    | suffix{x} "!" -> unwrap
    | suffix{x} "?." ID -> guard
    | suffix{x} "." ID -> property
    | suffix{x} tuple -> call
    | suffix{x} shape -> index
    | suffix{x} suite -> apply

//?composition{l}: l
//    | l l+ -> composition

?fw_composition{l, r}: l
    | l r+ -> fw_composition

?bw_composition{l, r}: r
    | l+ r -> fw_composition

?composition{x}.2: x
    | x composition{x} -> composition
    //| x x+ -> composition



?construct{x}: x 
    | x ".." x -> range // puede ir en una regla inferior
    | [x] "->" construct{x} -> lambda
    | x "=" construct{x} -> assign


//?tuple{x}: "(" element{x} ("," element{x})* ","? ")"
tuple: "(" (element ("," element)* ","?)? ")"
shape: "[" (element ("," element)* ","?)? "]"
suite: "{" statement* (element ("," element)* ","?)? "}"

//?element: expr [":" expr] ["=" expr] -> element

?element: [expr ":"] expr -> element
    | ".." [expr ":"] expr -> spread
    | ":" -> placeholder
    | ".." -> ellipsis


statement: ";"
    | expr ";" -> expr
    // | "if" simple_expr suite ["else" suite] -> if
    // | "for" expr "in" simple_expr suite -> for


if: "if" simple_expr suite ["else" suite]
for: "for" expr "in" simple_expr suite


// binary operators
?operators{x}: comparison{bitwise{arithmetic{x}}}

?comparison{x}: x 
    | x (_comparison_operator x)+ -> comparison

_comparison_operator: "==" | "!=" | "<>" | "<" | ">" | "<=" | ">="

?bitwise{x}: x
    | x (bitwise_operator x)+ -> bitwise

?bitwise_operator: "&" | "|" | "^" -> binary_operator

// arithmetic
?arithmetic{x}: addition{product{power{x}}}

?addition{x}: x
    | x (additive_operator x)+ -> addition

?additive_operator: "+" | "-" -> binary_operator

?product{x}: x
    | x (multiplicative_operator x)+ -> product

?multiplicative_operator: "*" | "/" | "%" -> binary_operator

?power{x}: x
    | x (power_operator x)+ -> power

?power_operator: "**" -> binary_operator

// prefix operators

?unary{x}: x
    | unary_operator+ x -> unary

unary_operator: "-" //| "+" | "!" | "~" | "#" | "$" | "@" | "&" | "*" | "^" 